export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const DASHBOARD_DETAILS = 'DASHBOARD_DETAILS';
export const LOGIN_DETAILS = 'LOGIN_DETAILS';
export const INVOICE_LIST = 'INVOICE_LIST';
export const PROFILE_DATA = 'PROFILE_DATA';
export const TASK_REPORT = 'TASK_REPORT';
export const SHORT_EXPIRY_LIST = 'SHORT_EXPIRY_LIST';
export const EXPIRY_PRODUCT_LIST = 'EXPIRY_PRODUCT_LIST';
export const DISTRIBUTORS_LIST = 'DISTRIBUTORS_LIST';
export const DISTRIBUTORS_PRODUCT_LIST = 'DISTRIBUTORS_PRODUCT_LIST';
export const DISTRIBUTORS_PRODUCT_COUNT = 'DISTRIBUTORS_PRODUCT_COUNT';
export const SALES_INVOICE_COUNT = 'SALES_INVOICE_COUNT';

